name: Generate XML Sitemap
on:
  push:
    branches: [ main ]

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://thegadfly.news/

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sitemap.xml
          git commit -m "update sitemap" || exit 0
          git push
